const Head = () => {
	return (
		<>
			<title>Lostark Hands Next</title>
			<meta
				content="width=device-width, initial-scale=1"
				name="viewport"
			/>
			<meta
				name="description"
				content="Generated by create next app"
			/>
			<link
				rel="manifest"
				href="/manifest.json"
			/>
			<meta
				name="theme-color"
				content="#317EFB"
			/>
		</>
	);
};

export default Head;
