const ENGRAVE_IMGAE: Record<string, string> = {
	각성: 'Buff/Buff_113.png',
	'강화 방패': 'Buff/Buff_239.png',
	'결투의 대가': 'Ability/Ability_224.png',
	구슬동자: 'Buff/Buff_18.png',
	'굳은 의지': 'Buff/Buff_44.png',
	'급소 타격': 'Buff/Buff_168.png',
	'기습의 대가': 'Buff/Buff_148.png',
	긴급구조: 'Ability/Ability_238.png',
	'달인의 저력': 'Buff/Buff_147.png',
	돌격대장: 'Buff/Buff_210.png',
	'마나의 흐름': 'Buff/Buff_63.png',
	'마나 효율 증가': 'Buff/Buff_166.png',
	바리케이드: 'Buff/Buff_170.png',
	'번개의 분노': 'Buff/Buff_191.png',
	'부러진 뼈': 'Buff/Buff_94.png',
	'분쇄의 주먹': 'Buff/Buff_83.png',
	불굴: 'Buff/Buff_66.png',
	선수필승: 'Achieve/achieve_08_62.png',
	속전속결: 'Ability/Ability_236.png',
	'슈퍼 차지': 'Achieve/achieve_06_14.png',
	승부사: 'Buff/Buff_136.png',
	'시선 집중': 'Ability/Ability_234.png',
	'실드 관통': 'Buff/Buff_89.png',
	아드레날린: 'Ability/Ability_235.png',
	'안정된 상태': 'Buff/Buff_105.png',
	'약자 무시': 'Achieve/achieve_04_30.png',
	'여신의 가호': 'Buff/Buff_229.png',
	'에테르 포식자': 'Buff/Buff_74.png',
	'예리한 둔기': 'Achieve/achieve_03_40.png',
	원한: 'Buff/Buff_71.png',
	'위기 모면': 'Buff/Buff_162.png',
	'저주받은 인형': 'Buff/Buff_237.png',
	전문의: 'Ability/Ability_237.png',
	'정기 흡수': 'Buff/Buff_65.png',
	'정밀 단도': 'Ability/Ability_239.png',
	'중갑 착용': 'Buff/Buff_46.png',
	'질량 증가': 'Ability/Ability_231.png',
	'최대 마나 증가': 'Buff/Buff_122.png',
	추진력: 'Ability/Ability_232.png',
	'타격의 대가': 'Ability/Ability_233.png',
	'탈출의 명수': 'Buff/Buff_10.png',
	'폭발물 전문가': 'Buff/Buff_121.png',
	'공격력 감소': 'Ability/Ability_218.png',
	'공격속도 감소': 'Ability/Ability_220.png',
	'방어력 감소': 'Ability/Ability_219.png',
	'이동속도 감소': 'Ability/Ability_221.png'
};

export default ENGRAVE_IMGAE;
