export default function Head() {
	return (
		<>
			<title>Lostark Hands Next</title>
			<meta
				content="width=device-width, initial-scale=1"
				name="viewport"
			/>
			<meta
				name="description"
				content="Generated by create next app"
			/>
			<link
				rel="manifest"
				href="/manifest.json"
			/>
			<link
				href="/icons/favicon-16x16.png"
				rel="icon"
				type="image/png"
				sizes="16x16"
			/>
			<link
				href="/icons/favicon-32x32.png"
				rel="icon"
				type="image/png"
				sizes="32x32"
			/>
			<link
				rel="apple-touch-icon"
				href="/apple-icon.png"
			></link>
			<meta
				name="theme-color"
				content="#317EFB"
			/>
		</>
	);
}
