name: Semver bump
on:
  push:
    branches:
      - main

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store

jobs:
  version:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: checkout code repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      # todo pnpm/action-setup@v2
      - name: install pnpm
        run: npm i pnpm@latest -g

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      # pr 생성 시 npmrc 파일은 만들어지지 않도록 changesets 액션 실행 전 만들어지도록 지정
      - name: Set up NPM credentials
        run: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}          
        
      - name: install dependencies
        run: pnpm install

      # 이게 참.. 하위의 모든 패키지가 배포가 된 경우에만 유용한것 같음. publish 액션이 돌 때, 하나라도 실패하는게 있으면 액션자체가 실패함
      # 성공한것들은 배포가 되긴 하는데, 액션 상태에 x 떠있으면 기분이 나빠서 ㅎ...
      # ignore필드에 명시해주려 해도, 모노레포 특징상 유일하게 배포하고자 하는 패키지가 배포를 원치 않는 패키지를 의존하는경우가 있는데,
      # 이 의존하고있는 패키지가 배포를 원치 않는다고 해서 ignore 해두면 그것만으로도 changeset에서 에러를 반환함.. 
      # 이 이유로.. 해당 액션은 테스트는 해보았으니 비활성화 하고자 함
      - name: create and publish versions
        uses: changesets/action@v1
        with:
          version: pnpm changeset version
          commit: "chore: update versions"
          title: "chore: update versions"
          publish: pnpm changeset publish
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  