name: "Deploy Storybook"

on:
  pull_request:
    branches: [ "main" ]
    paths:
      - 'packages/ui/**/*'

jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          
      - uses: pnpm/action-setup@v2
        with:
          version: 8.14.1

      - name: Install dependencies
        run: pnpm install

      - name: Publish to Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_TOKEN }}
          buildScriptName: "pnpm storybook:build"